{"name": "test_random", "status": "failed", "statusDetails": {"message": "AssertionError: Assertion failed. Expected 5 but was 7\nassert (5 + 2) == 5", "trace": "def test_random():\n        x=5\n        y=2\n>       assert x+y==5, \"Assertion failed. Expected 5 but was \" + str(x+y)\nE       AssertionError: Assertion failed. Expected 5 but was 7\nE       assert (5 + 2) == 5\n\npytest\\random_name_file_test.py:6: AssertionError"}, "start": 1674220918115, "stop": 1674220918116, "uuid": "9b51823f-65e9-4780-bd2a-d8eb868d7e70", "historyId": "4b0f53d0f1914afe1f51cf11630d06a1", "testCaseId": "5902e2a7a459a73b9e37995e433d0e83", "fullName": "pytest.random_name_file_test#test_random", "labels": [{"name": "parentSuite", "value": "pytest"}, {"name": "suite", "value": "random_name_file_test"}, {"name": "host", "value": "DESKTOP-4LISGQA"}, {"name": "thread", "value": "5036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest.random_name_file_test"}]}