{"name": "test_method_2", "status": "failed", "statusDetails": {"message": "AssertionError: Assertion failed. Expected 7\nassert (5 + 2) == 2", "trace": "def test_method_2():\n        x=5\n        y=2\n        assert x+y==7, \"Assertion failed. Expected 7\"\n>       assert x+y==2, \"Assertion failed. Expected 7\"\nE       AssertionError: Assertion failed. Expected 7\nE       assert (5 + 2) == 2\n\npytest\\test_pytest2.py:7: AssertionError"}, "start": 1674220936375, "stop": 1674220936376, "uuid": "104b4725-3fb0-474c-b35a-a60282718d52", "historyId": "2ec04f9ad85c513bb389a978a446225b", "testCaseId": "d127ef898284951892a59cba3bbf0f35", "fullName": "pytest.test_pytest2#test_method_2", "labels": [{"name": "parentSuite", "value": "pytest"}, {"name": "suite", "value": "test_pytest2"}, {"name": "host", "value": "DESKTOP-4LISGQA"}, {"name": "thread", "value": "5036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest.test_pytest2"}]}